"""huss migration(player,game,tournament,skilllevel

Revision ID: 12297afd5139
Revises: 
Create Date: 2026-02-13 16:29:24.485911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12297afd5139'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('player_white_id', sa.UUID(), nullable=True),
    sa.Column('player_black_id', sa.UUID(), nullable=True),
    sa.Column('result', sa.Enum('WHITE_WIN', 'BLACK_WIN', 'DRAW', name='win_state'), nullable=True),
    sa.Column('played_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('players',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('skill_level',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('rating_lower_bound', sa.Integer(), nullable=False),
    sa.Column('rating_upper_bound', sa.Integer(), nullable=False),
    sa.CheckConstraint('rating_lower_bound <= rating_upper_bound', name='ck_skill_valid_range'),
    sa.CheckConstraint('rating_lower_bound >= 0', name='ck_skill_lower_nonnegative'),
    sa.CheckConstraint('rating_upper_bound >= 0', name='ck_skill_upper_nonnegative'),
    sa.PrimaryKeyConstraint('title')
    )
    op.create_table('tournaments',
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='ck_tournament_valid_dates'),
    sa.PrimaryKeyConstraint('tournament_id')
    )
    op.create_table('mentors',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('mentor_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'mentor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mentors')
    op.drop_table('tournaments')
    op.drop_table('skill_level')
    op.drop_table('players')
    op.drop_table('games')
    # ### end Alembic commands ###
