"""huss migration updated init file and sql generator

Revision ID: 17bbcec0cb43
Revises: 12297afd5139
Create Date: 2026-02-13 16:51:38.982406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17bbcec0cb43'
down_revision: Union[str, Sequence[str], None] = '12297afd5139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('violations',
    sa.Column('violation_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('violation_type', sa.String(), nullable=False),
    sa.Column('violation_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('consequence', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('violation_id')
    )
    op.create_foreign_key(None, 'games', 'players', ['player_white_id'], ['player_id'])
    op.create_foreign_key(None, 'games', 'players', ['player_black_id'], ['player_id'])
    op.create_foreign_key(None, 'games', 'tournaments', ['tournament_id'], ['tournament_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_table('violations')
    # ### end Alembic commands ###
