from datetime import datetime, date
from typing import Protocol

from src.domain.game import Game, WinState


class GameRepositoryProtocol(Protocol):
    #CRUD:

    #C
    def add_game(self, game: Game) -> str: ...

    #R
    def get_all_games(self) -> list[Game]: ...

    def find_game_by_id(self, game_id: str) -> Game | None: ...
    def find_games_by_played_date(self, played_date: date) -> list[Game]: ...
    def find_games_by_result(self, result: WinState) -> list[Game]: ...
    def find_games_by_tournament_id(self, tournament_id: str) -> list[Game]: ...
    def find_games_by_player_white_id(self, player_white_id: str) -> list[Game]: ...
    def find_games_by_player_black_id(self, player_black_id: str) -> list[Game]: ...
    def find_games_by_player_id(self, player_id: str) -> list[Game]: ...


    #U
    def update_game_result(self, game_id: str, result: WinState) -> Game | None: ...
    def update_game_tournament_id(self, game_id: str, new_tournament_id: str) -> Game | None: ...
    def update_game_played_at(self, game_id: str, newDate: datetime) -> Game | None: ...

    def update_game_player_white_id(self, game_id: str, new_player_white_id: str) -> Game | None: ...

    def update_game_player_black_id(self, game_id: str, new_player_black_id: str) -> Game | None: ...


    #D
    def delete_game_by_id(self, game_id: str) -> str | None: ...
