from typing import Protocol
from src.domain.player import Player


class PlayerRepositoryProtocol(Protocol):
    # -- Create Operations --
    def add(self, player: Player) -> str: ...

    # -- Replace Operations --
    def replace(self, player_id: str, player: Player) -> str: ...

    # -- Read Operations --
    def get_all(self) -> list[Player]: ...

    def get_by_first_name(self, first_name: str) -> list[Player]: ...

    def get_by_last_name(self, last_name: str) -> list[Player]: ...

    def get_by_full_name(self, first_name: str, last_name: str) -> list[Player]: ...

    def get_by_rating(self, rating: int) -> list[Player]: ...

    def get_by_rating_range(
        self, rating_lower: int, rating_upper: int
    ) -> list[Player]: ...

    def get_by_id(self, player_id: str) -> Player: ...

    # -- Update Operations --
    def update_first_name_by_id(self, player_id: str, first_name: str) -> Player: ...

    def update_last_name_by_id(self, player_id: str, last_name: str) -> Player: ...

    def update_full_name_by_id(
        self, player_id: str, first_name: str, last_name: str
    ) -> Player: ...

    def update_rating_by_id(self, player_id: str, rating: int) -> Player: ...

    def update_rating_via_increment_by_id(
        self, player_id: str, rating_increment: int
    ) -> Player: ...

    # -- Delete Operations --
    def delete_by_id(self, player_id: str) -> Player: ...
