from typing import Protocol
from src.domain.violation import Violation


class ViolationRepositoryProtocol(Protocol):
    def add(self, violation: Violation) -> str: ...

    def get_all(self) -> list[Violation]: ...
    def get_by_id(self, violation_id: str) -> Violation: ...
    def get_by_player_id(self, player_id: str) -> list[Violation]: ...
    def get_by_game_id(self, game_id: str) -> list[Violation]: ...

    def update_by_id(self, violation_id: str, payload) -> Violation: ...

    def delete_by_id(self, violation_id: str) -> Violation: ...